### ISSUE TITLE
Get estimates for Atonomi transactions

### ISSUE THREAD

**Issue by filcap** [atonomi/smart-contracts#59]
Create script to output gas estimations for all transactions to feed into financial models
- Registration
- Activation
- Reputation
- Add Admin
- Add Manufacturer

**Comment by filcap** [comment]
When you get back, lets reprioritize this as well.  

- create a gas.estimates.test.js
- similar to how you extracted each estimate, just create a test for each estimate and print it out as the test
- example: 

```
describe('manufacturer costs') {
     // compute gas
     it('registerDevice() = ${gas}') { /* empty test */ }
}
```

**Comment by micahu** [comment]
completed with previous commit
